- name: distro information is detected
  set_fact:
    distro:
      name: "{{ ansible_distribution | lower }}"
      release: "{{ ansible_distribution_release }}"
      arch: "{{ ansible_architecture | replace('x86_64', 'amd64') }}"

- name: apt https repository requirements are satisfied
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: docker-ce repository signing key is registered
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: docker-ce repository is registered
  apt_repository:
    repo: deb [arch={{ distro.arch }}] https://download.docker.com/linux/{{ distro.name }} {{ distro.release }} stable
    state: present

- name: docker-ce is installed
  apt:
    name: docker-ce
    state: present

- name: docker-ce service is up
  service:
    name: docker
    state: started
    enabled: yes
